// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKOR7A6Wyb5BOBERAbJESGArYD4RjnTkU',
    appId: '1:503424929660:web:e35fa223ed570c72151ef9',
    messagingSenderId: '503424929660',
    projectId: 'spacesense-ai',
    authDomain: 'spacesense-ai.firebaseapp.com',
    databaseURL: 'https://spacesense-ai-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spacesense-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcRKWsp6UCUnDvqV18OVXt01_xHnI2q8U',
    appId: '1:503424929660:android:0912ae88990411e3151ef9',
    messagingSenderId: '503424929660',
    projectId: 'spacesense-ai',
    databaseURL: 'https://spacesense-ai-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spacesense-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARtOmoyMhh_F6C_UBSXFGSEPs-EX_u7uc',
    appId: '1:503424929660:ios:e76e2bb7b24cc7bc151ef9',
    messagingSenderId: '503424929660',
    projectId: 'spacesense-ai',
    databaseURL: 'https://spacesense-ai-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spacesense-ai.firebasestorage.app',
    iosClientId: '503424929660-1qvtfu3jnkcbus7thn3qss0hu92khvir.apps.googleusercontent.com',
    iosBundleId: 'com.spacesense.ai.spacesenseAi',
  );
}
